plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "G:\\내 드라이브\\ANTI GRAVITY\\전문상담임용고시\\timestamp-camera"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]